shiviti/config/routes.rb
Rails.application.routes.draw do
  resources :reminders
  resources :meditations
  devise_for :users

  root 'welcome#index'

  get '/progress' => 'welcome#progress'

end

shiviti/app/models/meditation.rb
class Meditation < ActiveRecord::Base
	belongs_to :user
end

shiviti/app/models/reminder.rb
class Reminder < ActiveRecord::Base
	validates :phone_number, presence: true
  validates :time, presence: true
  belongs_to :user

  after_create :alert

  @@ALERT_TIME = 1.second # minutes before appointment

  # Notify our appointment attendee X minutes before the appointment time
  def alert
    # @twilio_number = ENV['TWILIO_NUMBER']
    # @client = Twilio::REST::Client.new ENV['TWILIO_ACCOUNT_SID'], ENV['TWILIO_AUTH_TOKEN']
     # binding.pry
    number_to_send_to = self.phone_number

	  twilio_sid = "ACca4bce79e5cdb95990cdf5a84b89c45b"
	  twilio_token = "5f5703217d9812afe53c1fceea9d0b3f"
	  twilio_phone_number = "5404694050"

	  @twilio_client = Twilio::REST::Client.new twilio_sid, twilio_token
    # time_str = ((self.time).localtime).strftime("%I:%M%p on %b. %d, %Y")
    reminder = "Hi 😍 This is a reminder from the Shiviti App. Happy Meditating 🙏"
    
    # @twilio_client.account.sms.messages.create
    message = @twilio_client.account.messages.create(
      :from => "+1#{twilio_phone_number}",
      :to => number_to_send_to,
      :body => reminder,
    )
    puts message.to
  end

  def when_to_run
    time - @@ALERT_TIME
  end

  handle_asynchronously :alert, :run_at => Proc.new { |i| i.when_to_run }


end

shiviti/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :meditations
   has_many :reminders
end

shiviti/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # before_filter :set_user_time_zone

  # def set_user_time_zone
  #   Time.zone = "EST"
  #   #current_user.time_zone
  #   # => #<ActiveSupport::TimeZone:0x007fb80d1374d8 @name="Pacific/Honolulu" [...] >
  # end
end

shiviti/app/controllers/meditations_controller.rb
class MeditationsController < ApplicationController
  before_action :set_meditation, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /meditations
  # GET /meditations.json
  def index
    @meditations = Meditation.all
  end

  # GET /meditations/1
  # GET /meditations/1.json
  def show
  end

  # GET /meditations/new
  def new
    @meditation = current_user.meditations.build
  end

  # GET /meditations/1/edit
  def edit
  end

  # POST /meditations
  # POST /meditations.json
  def create
    @meditation = current_user.meditations.build(meditation_params)
    length_in_seconds = @meditation.end_time - @meditation.start_time
    minutes = (length_in_seconds / 60) % 60
    @meditation.length = minutes.floor

    respond_to do |format|
      if @meditation.save
        format.html { redirect_to @meditation, notice: 'Meditation was successfully created.' }
        format.json { render :show, status: :created, location: @meditation }
      else
        format.html { render :new }
        format.json { render json: @meditation.errors, status: :unprocessable_entity }
      end
    end
    # binding.pry
  end



  # PATCH/PUT /meditations/1
  # PATCH/PUT /meditations/1.json
  def update
    respond_to do |format|
      if @meditation.update(meditation_params)
        format.html { redirect_to @meditation, notice: 'Meditation was successfully updated.' }
        format.json { render :show, status: :ok, location: @meditation }
      else
        format.html { render :edit }
        format.json { render json: @meditation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meditations/1
  # DELETE /meditations/1.json
  def destroy
    @meditation.destroy
    respond_to do |format|
      format.html { redirect_to meditations_url, notice: 'Meditation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meditation
      @meditation = Meditation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meditation_params
      params.require(:meditation).permit(:user_id, :note, :start_time, :end_time, :before_mood, :after_mood)
    end
end

shiviti/app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_action :set_reminder, only: [:show, :edit, :update, :destroy]

  # GET /reminders
  # GET /reminders.json
  def index
    @reminders = Reminder.all
     if @reminders.length == 0
      flash[:alert] = "You have no appointments. Create one now to get started."
    end
    # binding.pry
  end

  # GET /reminders/1
  # GET /reminders/1.json
  def show
  end

  # GET /reminders/new
  def new
    @reminder = current_user.reminders.build
  end

  # GET /reminders/1/edit
  def edit
  end

  # POST /reminders
  # POST /reminders.json
  def create
    Time.zone = "EST"
    @reminder = current_user.reminders.build(reminder_params)

    respond_to do |format|
      if @reminder.save
        format.html { redirect_to @reminder, notice: 'Reminder was successfully created.' }
        format.json { render :show, status: :created, location: @reminder }
      else
        format.html { render :new }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reminders/1
  # PATCH/PUT /reminders/1.json
  def update
    respond_to do |format|
      if @reminder.update(reminder_params)
        format.html { redirect_to @reminder, notice: 'Reminder was successfully updated.' }
        format.json { render :show, status: :ok, location: @reminder }
      else
        format.html { render :edit }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reminders/1
  # DELETE /reminders/1.json
  def destroy
    @reminder.destroy
    respond_to do |format|
      format.html { redirect_to reminders_url, notice: 'Reminder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reminder
      @reminder = Reminder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reminder_params
      params.require(:reminder).permit(:phone_number, :time, :user_id)
    end
end

shiviti/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@api_key = ENV["GOOGLE_API"]
		# binding.pry
	end

	def progress
	end

	# def send_text_message(number)
	#   number_to_send_to = number

	#   twilio_sid = "ACca4bce79e5cdb95990cdf5a84b89c45b"
	#   twilio_token = "5f5703217d9812afe53c1fceea9d0b3f"
	#   twilio_phone_number = "5404694050"

	#   @twilio_client = Twilio::REST::Client.new twilio_sid, twilio_token

	#   @twilio_client.account.sms.messages.create(
	#     :from => "+1#{twilio_phone_number}",
	#     :to => number_to_send_to,
	#     :body => "This is a reminder from the Shiviti App. Happy Meditating :)"
	#   )
	# end
end

shiviti/app/helpers/application_helper.rb
module ApplicationHelper
end

shiviti/app/helpers/meditations_helper.rb
module MeditationsHelper
end

shiviti/app/helpers/reminders_helper.rb
module RemindersHelper
end

shiviti/app/helpers/welcome_helper.rb
module WelcomeHelper
end

shiviti/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shiviti</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
  <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  <!-- <script src="Chart.js"></script> -->


</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p> <br>

<!-- &callback=initMap -->
<%= yield %>
<video autoplay id="video" class="blur" loop>
	<source src="http://cdn.calm.com/scenes/scene-Qqkzy9k7Eo.mp4?v=1418162238190" type="video/mp4">
</video>


</body>
</html>

shiviti/app/views/meditations/_form.html.erb
<%= form_for(@meditation) do |f| %>
  <% if @meditation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meditation.errors.count, "error") %> prohibited this meditation from being saved:</h2>

      <ul>
      <% @meditation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div> -->
<div class="center">


  <div class="start">
    <div class ="midnight">
    
      <div class="field">
        <%= f.label :start_time %><br>
        <%= f.time_select :start_time, {:ampm => true} %>
      </div>
      <div class="field">
        <%= f.label :before_mood %><br>
        <%= f.text_field :before_mood %>
      </div>
      </div>

  </div>

<div class="round-button"><button class="start_button start">Start</button> </div> <br>

<div class="round-button"> <button class="end_button end">End</button> </div> <br>


<div class="end">

  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.time_select :end_time, {:ampm => true} %>
  </div>

  <div class="field">
    <%= f.label :after_mood %><br>
    <%= f.text_field :after_mood %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_area :note %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

</div>
<% end %>

</div>

shiviti/app/views/meditations/edit.html.erb
<h1>Editing Meditation</h1>

<%= render 'form' %>

<%= link_to 'Show', @meditation %> |
<%= link_to 'Back', meditations_path %>

shiviti/app/views/meditations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Meditations</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Note</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Before mood</th>
      <th>After mood</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meditations.each do |meditation| %>
      <tr>
      <% if meditation.user == current_user %>
        <td><%= meditation.user_id %></td>
        <td><%= meditation.note %></td>
        <td><%= meditation.start_time %></td>
        <td><%= meditation.end_time %></td>
        <td><%= meditation.before_mood %></td>
        <td><%= meditation.after_mood %></td>
        <td><%= link_to 'Show', meditation %></td>
        <td><%= link_to 'Edit', edit_meditation_path(meditation) %></td>
        <td><%= link_to 'Destroy', meditation, method: :delete, data: { confirm: 'Are you sure?' } %></td>

        <% end %> 
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meditation', new_meditation_path %>

shiviti/app/views/meditations/new.html.erb
<h1 class="start heading">Let's start meditating</h1>

<%= render 'form' %>

<!-- link_to 'Back', meditations_path  -->

shiviti/app/views/meditations/show.html.erb
<p id="notice"><%= notice %></p>

<!-- <p>
  <strong>User:</strong>
  <%= @meditation.user_id %>
</p> -->



<!-- <p>
  <strong>Start time:</strong>
  <%= @meditation.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @meditation.end_time %>
</p> -->

<p> You meditated from <%= @meditation.start_time.strftime("%H:%M")%> to <%= @meditation.end_time.strftime("%H:%M")%> 😍 That is <%=@meditation.length %> minutes. 
</p>

<p>
  <strong>Before mood:</strong>
  <%= @meditation.before_mood %>
</p>

<p>
  <strong>After mood:</strong>
  <%= @meditation.after_mood %>
</p>

<p>
  <strong>Note:</strong>
  <%= @meditation.note %>
</p>
<%= link_to 'Home', root_path %>
<!-- 
<%= link_to 'Edit', edit_meditation_path(@meditation) %> |
<%= link_to 'Back', meditations_path %>
 -->

shiviti/app/views/reminders/_form.html.erb
<%= form_for(@reminder) do |f| %>
  <% if @reminder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reminder.errors.count, "error") %> prohibited this reminder from being saved:</h2>

      <ul>
      <% @reminder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
    <div class="form-group">
    <%= f.label :time, "Time and Date" %>
    <!-- Rails expects time_select when dealing with ActiveRecord forms -->
    <div class="col-lg-2">
      <%= time_select :reminder, :time, {:ampm => true} %>
    </div>
    <div class="col-lg-4">
      <%= date_select :reminder, :time, {:class => "form-control" } %>
    </div>
    
  </div>
  <!-- <div class="field">
    <%= f.label :time %><br>
    <%= f.datetime_select :time %>
  </div> -->
 <!--  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div> -->
<br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

shiviti/app/views/reminders/edit.html.erb
<h1>Editing Reminder</h1>

<%= render 'form' %>

<%= link_to 'Show', @reminder %> |
<%= link_to 'All Reminders', reminders_path %>
<%= link_to 'Home', root_path %>

shiviti/app/views/reminders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reminders</h1>

<table>
  <thead>
    <tr>
      <th>Phone number</th>
      <th>Time</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reminders.each do |reminder| %>
      <tr>
        <td><%= reminder.phone_number %></td>
        <td><%= reminder.time.strftime('%H:%M %p, %b %d, %Y')  %></td>
        <td><%= reminder.user_id %></td>
        <td><%= link_to 'Show', reminder %></td>
        <td><%= link_to 'Edit', edit_reminder_path(reminder) %></td>
        <td><%= link_to 'Destroy', reminder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reminder', new_reminder_path %> <br>
<%= link_to 'Home', root_path %>

shiviti/app/views/reminders/new.html.erb
<h4>Select the time and date and we will send you a reminder to meditate</h4>

<%= render 'form' %>

<%= link_to 'All Reminders', reminders_path %> <br>
<%= link_to 'Home', root_path %>

shiviti/app/views/reminders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Phone number:</strong>
  <%= @reminder.phone_number %>
</p>

<p>
  <strong>Time:</strong>
  <%= @reminder.time.strftime('%H:%M %p, %b %d, %Y') %>
</p>

<!-- <p>
  <strong>User:</strong>
  <%= @reminder.user_id %>
</p> -->

<%= link_to 'Edit', edit_reminder_path(@reminder) %> |
<%= link_to 'Back', reminders_path %>

shiviti/app/views/welcome/index.html.erb
<% if user_signed_in? %>

<div class="links">
	<%= link_to "Sign out", destroy_user_session_path, method: :delete %> <br>

	<%= link_to "Meditate Now", new_meditation_path %> <br>
	<%= link_to "See my Progress", progress_path %> <br>

	<%= link_to "Create a reminder", new_reminder_path %> <br>
	
 </div>

	<button class="location">Find a place nearby to meditate</button> <br>
	<div id="map"> </div>
	<p id="error"></p>

	<script>
		$(document).ready(function () {
			$("#video").removeClass("blur");
		});
	</script>

<% else %>
	<h1 class="shiviti"> Shiviti </h1>

	<div class="login">
		<%= link_to "login/", user_session_path %> 

		<%= link_to "new user", new_user_registration_path %> 
	</div>

	<script>
		$(document).ready(function () {
			$("#video").removeClass("blur");
		});
	</script>

	<div class="welcome">
		<p> Welcome to Shiviti </p>
		<p> Relax with Shiviti, a simple mindfulness meditation <br> app that brings clarity and peace of mind into your life.</p>

	</div>
	<style>
/*body { 
  background: url("http://cdn.calm.com/scenes/scene-Qqkzy9k7Eo.mp4?v=1418162238190") no-repeat center center fixed; 
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}*/
</style>

<% end %>

<script src="https://maps.googleapis.com/maps/api/js?key=<%=@api_key%>&libraries=places" async defer></script>

shiviti/app/views/welcome/progress.html.erb
<script>
	
$(document).ready(function(){
	

var ctx = $("#myChart").get(0).getContext("2d");
				
		var data = {
	    labels: <%= current_user.meditations.map { |meditation| meditation.start_time.strftime('%B')}.to_json.html_safe%>,
	    datasets: [
	      {
	          label: "My First dataset",
	          fillColor: "rgba(220,220,220,0.2)",
	          strokeColor: "rgba(220,220,220,1)",
	          pointColor: "rgba(220,220,220,1)",
	          pointStrokeColor: "#fff",
	          pointHighlightFill: "#fff",
	          pointHighlightStroke: "rgba(220,220,220,1)",
	          data: <%=current_user.meditations.map(&:length)%>
	        
	      },
	    ]
		};
		var myLineChart = new Chart(ctx).Line(data, {
     scaleFontColor: "#fff" });
});


</script>
<canvas id="myChart" width="400" height="400"></canvas>
<br>
<%= link_to 'Home', root_path %>